### ISSUE TITLE
log to custom URL via https

### ISSUE THREAD

**Issue by ThomasRgbg** [mendhak/gpslogger#374]
Hi, 

I'm using a NexusS running CM11 (so Android 4.4.4)

When I want to use the log to custom URL, I get an ssl error in the debug log. 
```
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206) ~[na:0.0]
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345) ~[na:0.0]
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296) ~[na:0.0]
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503) ~[na:0.0]
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136) ~[na:0.0]
	at com.mendhak.gpslogger.loggers.customurl.CustomUrlJob.onRun(CustomUrlJob.java:94) ~[na:0.0]
	at com.path.android.jobqueue.Job.safeRun(Job.java:145) ~[na:0.0]
	at com.path.android.jobqueue.JobHolder.safeRun(JobHolder.java:90) ~[na:0.0]
	at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:306) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x53139ee0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x512add74:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406) ~[na:0.0]
	... 14 common frames omitted
21:09:53 DEBUG CustomUrlJob.onRun:75 - Sending to URL: https://thisismyhost.de/gps/gps.php?lat=48.98941562330501&lon=12.077085230633907
21:10:23 DEBUG GpsLoggingService.StopLogging:417 - .
21:10:23 DEBUG GpsLoggingService.StopGpsManager:621 - Removing towerLocationManager updates
21:10:23 DEBUG GpsLoggingService.StopGpsManager:626 - Removing gpsLocationManager updates
21:10:23 DEBUG GpsLoggingService.StopPassiveManager:638 - Removing passiveLocationManager updates
21:10:23 DEBUG GpsLoggingService.StopActivityRecognitionUpdates:135 - Stopping activity recognition updates
21:10:23 INFO  GpsLoggingService.NotifyClientStopped:694 - Stopped
21:10:23 DEBUG GpsSimpleViewFragment.OnWaitingForLocation:468 - false
21:10:52 DEBUG GpsMainActivity.StopAndUnbindServiceIfRequired:971 - Stopping the service
21:10:52 WARN  GpsLoggingService.onDestroy:168 - GpsLoggingService is being destroyed by Android OS.
```
Well, the server is configured pretty tight and supports only TLS 1.2. To my knowledge, this should be supported by Android 4.4 and up. (The browser could access the website pretty well)

I don't like to downgrade the server again to the not secure TLS versions again, so is there a way to fix this on the client side ?

**Comment by mendhak** [comment]
I've now enabled TLS.  

On my phone (CM 12.1.1) it was able to support : SSLv3, TLSv1, TLSv1.1, TLSv1.2

I think depending on the Android version, some users will not be able to use later TLS versions.

**Comment by mendhak** [comment]
`v70 released and will appear in market in a few hours. Closing this thread. Please create a new issue if there are further problems.`
