### ISSUE TITLE
SFP Test Failed "Pipe closed"

### ISSUE THREAD

**Issue by apexo** [mendhak/gpslogger#536]
The SFTP Test fails for me. First tried with an ed25519 key, which was rejected (Invalid private key), then tried again with an RSA key. This worked better. It asked me to accept the fingerprint, but when uploading, it fails:

```
05-04 11:37:21.084 14674 18179 E SFTPJob : com.jcraft.jsch.JSchException: java.io.IOException: Pipe closed
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.jcraft.jsch.ChannelSftp.start(ChannelSftp.java:315) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.jcraft.jsch.Channel.connect(Channel.java:152) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.jcraft.jsch.Channel.connect(Channel.java:145) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.mendhak.gpslogger.senders.sftp.SFTPJob.onRun(SFTPJob.java:77) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.path.android.jobqueue.Job.safeRun(Job.java:145) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.path.android.jobqueue.JobHolder.safeRun(JobHolder.java:90) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:306) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob : Caused by: java.io.IOException: Pipe closed
05-04 11:37:21.084 14674 18179 E SFTPJob :      at java.io.PipedInputStream.read(PipedInputStream.java:319) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at java.io.PipedInputStream.read(PipedInputStream.java:394) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2909) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2935) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      at com.jcraft.jsch.ChannelSftp.start(ChannelSftp.java:262) ~[na:0.0]
05-04 11:37:21.084 14674 18179 E SFTPJob :      ... 7 common frames omitted
```

(freshly built from git 03e0243b43b7410ab7a76800603fd34aaf80a621 / "v87 market release")

**Comment by apexo** [comment]
Similarly, when (auto-)uploading a file, I get "inputstream is closed":
```
05-04 11:44:50.450 14674 22519 D SFTPJob : onRun:75 - Connected, opening SFTP channel
05-04 11:44:50.539 14674 22519 E SFTPJob : onRun:98 - java.io.IOException: inputstream is closed
05-04 11:44:50.539 14674 22519 E SFTPJob : com.jcraft.jsch.JSchException: java.io.IOException: inputstream is closed
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.jcraft.jsch.ChannelSftp.start(ChannelSftp.java:315) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.jcraft.jsch.Channel.connect(Channel.java:152) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.jcraft.jsch.Channel.connect(Channel.java:145) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.mendhak.gpslogger.senders.sftp.SFTPJob.onRun(SFTPJob.java:77) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.path.android.jobqueue.Job.safeRun(Job.java:145) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.path.android.jobqueue.JobHolder.safeRun(JobHolder.java:90) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:306) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob : Caused by: java.io.IOException: inputstream is closed
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2911) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2935) ~[na:0.0]
05-04 11:44:50.539 14674 22519 E SFTPJob :      at com.jcraft.jsch.ChannelSftp.start(ChannelSftp.java:262) ~[na:0.0]
```

**Comment by apexo** [comment]
Sorry, my fault. Apparently, disabling login (by setting the shell to /bin/false) also disables sftp …

**Comment by mendhak** [comment]
Hey thanks for updating it, at least I will keep this in mind for the future if someone else has such a problem!  If you're trying to restrict, could you play around with [setting up a chroot jail](http://www.thegeekstuff.com/2012/03/chroot-sftp-Setup/) which does look complicated. Also [scponly](https://github.com/scponly/scponly/wiki), but I have not tested with either of these setups.

**Comment by apexo** [comment]
IMO, setting up a chroot jail is quite easy. If you already have a dedicated user with a home directory for that purpose, then it's just a matter of adding
```
Match User username_here
  ChrootDirectory %h
  ForceCommand internal-sftp
```
to `/etc/ssh/sshd_config` and `chown root ~username_here`

gpslogger uploads work fine with this setup (the upload path may need to be adjusted, I used an absolute path which needed to be adjusted for the chroot).
