### ISSUE TITLE
Name is being added to Custom URL

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [mendhak/gpslogger#587]
Hi, I'm testing with a url on my lan:  http://192.168.10.135:2000/?lat=%LAT&lon=%LON

I can hit that url from my phone browser, but it seems GPSLogger is adding _**my name**_ before the url?

Please how can I disable this? (see debug logs)
```
22:15:19 DEBUG CustomUrlJob.onRun:64 - Sending to URL: Charles Okwuagwu:
http://192.168.10.135:2000?lat=6.32845566&lon=3.3364563333
22:15:19 DEBUG Networks.getKnownServersStore:52 - Getting local truststore - /storage/emulated/0/Android/data/com.mendhak.gpslogger/files/knownservers.bks
22:15:19 ERROR AppSettings$1.e:96 - error while executing job com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@e6fe4fc
java.lang.IllegalArgumentException: unexpected url: Charles Okwuagwu:
http://192.168.10.135:2000?lat=6.32845566&lon=3.3364563333
 at okhttp3.Request$Builder.url(Request.java:143) ~[na:0.0]
 at com.mendhak.gpslogger.loggers.customurl.CustomUrlJob.onRun(CustomUrlJob.java:92) ~[na:0.0]
 at com.path.android.jobqueue.Job.safeRun(Job.java:145) ~[na:0.0]
 at com.path.android.jobqueue.JobHolder.safeRun(JobHolder.java:90) ~[na:0.0]
 at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:306) ~[na:0.0]
 at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
```

**Comment by mendhak** [comment]
Yep definitely a weird one - can you post a screenshot of your URL textbox within custom URL settings, checking for any spacing before/after.  

It appears that the URL is of two *lines* and the first one is your name, somehow, followed by the actual http:.., so OKHTTP is definitely seeing some weirdness there.

**Comment by CharlesOkwuagwu** [comment]
damn ... just seen it ... I copied the name in by mistake.

Thanks!

**Comment by mendhak** [comment]
Bwahaha, glad you found it :grin:
