### ISSUE TITLE
Sharing file causes android.os.FileUriExposedException

### ISSUE THREAD

**Issue by mendhak** [mendhak/gpslogger#675]
When sharing a file via the bottom sharing icon,  app crashes with this exception:

> Process: com.mendhak.gpslogger, PID: 21951
>     android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.mendhak.gpslogger/files/20180912.gpx exposed beyond app through ClipData.Item.getUri()
>         at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
>         at android.net.Uri.checkFileUriExposed(Uri.java:2356)
>         at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
>         at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
>         at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
>         at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
>         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1795)
>         at android.app.Activity.startActivityForResult(Activity.java:4495)
>         at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
>         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
>         at android.app.Activity.startActivityForResult(Activity.java:4453)
>         at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
>         at android.app.Activity.startActivity(Activity.java:4814)
>         at android.app.Activity.startActivity(Activity.java:4782)
>         at com.mendhak.gpslogger.GpsMainActivity$14.onSelection(GpsMainActivity.java:1127)
>         at com.afollestad.materialdialogs.MaterialDialog.sendMultiChoiceCallback(MaterialDialog.java:393)
>         at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:416)
>         at android.view.View.performClick(View.java:6303)
>         at android.view.View$PerformClick.run(View.java:24828)
>         at android.os.Handler.handleCallback(Handler.java:789)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6798)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by mendhak** [comment]
v97 released to market
