### ISSUE TITLE
Android 4 - Google Drive upload fails due to HTTP PATCH method

### ISSUE THREAD

**Issue by mendhak** [mendhak/gpslogger#676]
On Android 4.x, Google Drive uploads are failing with this stack trace

> Unknown method 'PATCH'; must be one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE]
> java.net.ProtocolException: Unknown method 'PATCH'; must be one of [OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE]
> at java.net.HttpURLConnection.setRequestMethod(HttpURLConnection.java:677)
> at libcore.net.http.HttpsURLConnectionImpl.setRequestMethod(HttpsURLConnectionImpl.java:144)
> at com.mendhak.gpslogger.senders.googledrive.GoogleDriveJob.updateFileContents(GoogleDriveJob.java:125)
> at com.mendhak.gpslogger.senders.googledrive.GoogleDriveJob.onRun(GoogleDriveJob.java:107)
> at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
> at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
> at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407)
> at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326)
> at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354)
> at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
> at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389)
> at java.lang.Thread.run(Thread.java:856)

Potential solution: https://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch

    conn.setRequestProperty("X-HTTP-Method-Override", "PATCH");

(But how will I test this?)

**Comment by mendhak** [comment]
v98 released to market
