### ISSUE TITLE
customurl: improve SSL certificate verification step

### ISSUE THREAD

**Issue by glpatcern** [mendhak/gpslogger#677]
Hi there,

Partially related to https://github.com/mendhak/gpslogger/issues/627 - I use gpslogger against an https server with a Let's Encrypt certificate (which is renewed every 3 months). The issue is that, even if the certificate as well as its CA chain are trusted (and the hostname matches the SAN), I need to manually include it in some verified list of certificates by executing the HTTP test, otherwise the app never executes the HTTP GET request. I realized this by pure chance because gpslogger suddenly stopped working, and re-executing the HTTP test (and accepting the new certificate) it started to work again.

Any chance that the SSL verification step can simply go ahead for new certificates when their CA is already trusted?

Thanks in advance for the great app!

**Comment by mendhak** [comment]
You should know I've removed the HTTP Test feature - it was causing a lot of confusion among users. 

But to your question if the SAN contains the hostname you're calling there shouldn't be any problem.  I also use Let's Encrypt for one of my sites, works just fine.   You can set up [debug logging](https://gpslogger.app/#troubleshooting) to capture the actual exception.  You can also tell me the domain you're trying to work against (or just mail it to me gpslogger @ mendhak.com ) and I can post some dummy entries like `https://example.com/?a=blahblah` to see what the error is.

**Comment by glpatcern** [comment]
[Sorry for the confusion, I actually meant that "Validate SSL Certificate" option, not the HTTP test which indeed disappeared]
Thanks for the tip about the debug logging, I'll make sure to enable it as soon as my current Let's Encrypt certificate expires - that is end of October - and I will come back to you. Anyway, good to know that a priori Let's Encrypt certs should just work as they're issued from a well-known CA as opposed to self-signed ones.

**Comment by mendhak** [comment]
Ah so you mean - when the cert changed you had to re-execute Validate SSL Certificate.  

When you did that, were you shown the dialog [like you see here](https://gpslogger.app/#customsslcertificates) ? Or did it simply say everything's OK. 

If you're using LE and you see that dialog then that is unusual.  What Android OS version?  It could be on older OSes and older Google Play Services the LE CA wasn't present. And was added at some point - but I can't figure out when.

**Comment by glpatcern** [comment]
Yep exactly, and I saw that dialog (whereas now it says everything is OK).

I concur with you that it could be the LE CA not present. Android version is 7.0 (Huawei). Do you know how I can look for the registered CAs on my phone?

**Comment by mendhak** [comment]
go to settings, search for credential storage,  then trusted credentials.
Under there look for digital signature trust co. They cross sign for LE

I'm attaching a screenshot, hopefully github will include it via email

**Comment by mendhak** [comment]
https://ibb.co/m4pEKz
Screenshot

**Comment by mendhak** [comment]
![image](https://user-images.githubusercontent.com/746276/45590386-08615c80-b92f-11e8-9cb7-4e5fb28eb3d2.png)

**Comment by mendhak** [comment]
In your list look for `Digital Signature Trust Co.` rather than Let's Encrypt.  Try disabling that then browsing to Let's Encrypt or your site. Then re-enable it.  I don't think you will actually find LE in that list,I don't have it either.

So what you can do is when the problem occurs next time instead of re-validating just enable debug logging.  Let the logging start and fail on custom URL logging - that way the exception will get captured, then we can look at the file.

**Comment by glpatcern** [comment]
OK so I found it, but oddily disabling it did not trigger any warning on Chrome opening letsencrypt.org (even in an incognito window). Anyway, I'll do as you suggested so we try and understand what happens once I get the new certificate - please keep this on hold ;)

**Comment by Jaydubya35** [comment]
Hey guys, I'm having the same issue. I will email you the debug logs shortly.

**Comment by Jaydubya35** [comment]
To recap, I have the Digital Signature Trust Co CA turned on and working (disabling it gives me an SSL error for letsencrypt.org). I can use the Validate SSL to trust it. I have sent you the debug logs (via email posted prior) from before validating.

**Comment by mendhak** [comment]
I got the debug file. I'll be sending some dummy requests to your domain to reproduce the error.

**Comment by mendhak** [comment]
I've been able to send a bunch of requests from multiple phones to `/?issue=677&test=true` 

In each case I had to Validate the cert to trust it.  

When a certificate has been validated manually and stored, the debug log should show:

> in keystore: true

But yours is showing

> in keystore: false

Did you click OK on the Validate Cert dialog and the restart the application?

If you have a file manager you can also go look at `/storage/emulated/0/Android/data/com.mendhak.gpslogger/files` and look for the file `knownservers.bks` - that's where the CAs get stored if you have to verify manually.

**Comment by mendhak** [comment]
And a way to start over is to delete that .bks file, all the cert validation will have to be done again.

**Comment by Jaydubya35** [comment]
> In each case I had to Validate the cert to trust it.

Ok, so you are able to see and reproduce the problem. The cert is valid and signed from a trusted CA so it should validate that it trusts the entity that _signed_ the cert, not the cert itself as it rotates.

Yes, I can click the Validate SSL and then click OK (which I have done) to get it to work, but I get a new cert every 60-90 days and shouldn't have to. If this was a self-signed cert I can totally see the reason I would need to validate.

**Comment by mendhak** [comment]
I believe what's missing is the certificate chain from the web server.

I looked for a working domain with Let's Encrypt, try this:

    openssl s_client -connect palass.org:443

And at the top you'll see a chain and it should look like so

![image](https://user-images.githubusercontent.com/746276/46408185-2f7aa500-c709-11e8-810e-131e7f089093.png)

I tried against your domain, but there is no chain.  So the app just gets a cert and _thinks_ it's self signed, so you see that validation dialog. 

The reason browsing to that domain works in a browser is because browsers will go and fetch the CAs up the chain behind the scenes - that's why sometimes when you hit a site for the first time, if it's missing the chain, it doesn't work.  You refresh and it works.  In that intervening time the browser downloaded the certs.    

Apps can't really do that though as we're using low level libraries.

**Comment by Jaydubya35** [comment]
Thank you for the explanation. I have updated my ngingx to use the `fullchain.pem` instead of just the `cert.pem`. I deleted my `knownservers.bks` and checked, but not sure if it worked correctly. Do you mind verifying it is working for you?

**Comment by mendhak** [comment]
Hey I just tried the `openssl` command and I can see a chain now.  In GPSLogger after deleting the BKS I can validate against your site now without problem, no extra dialog appears.  

@glpatcern  this may be the same issue for you, you'll need to ensure your web server is presenting the full chain.

**Comment by glpatcern** [comment]
Hi, thanks for the input. I tried with my domain prior to any change and I see the following:
```
$ openssl s_client -connect lopresti.[mydomain]:443                                                                                                          Oct 03, 14:36 CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = lopresti.[mydomain]
verify return:1
---
Certificate chain
 0 s:/CN=lopresti.[mydomain]
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
 2 s:/O=Digital Signature Trust Co./CN=DST Root CA X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
```
(I replaced my actual domain with `[mydomain]`, but I've no problems in giving you the full name if needed).
This seems like the full chain is exposed, right?
I can check on the server for the full `.pem` file later today.

**Comment by glpatcern** [comment]
Hi,

My certificate got renewed and I have generated the debug log as suggested. I can send it by email but the relevant part is here:
```
10:39:30 DEBUG Networks.getKnownServersStore:52 - Getting local truststore - /storage/emulated/0/Android/data/com.mendhak.gpslogger/files/knownservers.bks
10:39:30 DEBUG AppSettings$1.d:92 - Job queue idle. next job at: null
10:39:30 DEBUG AppSettings$1.d:92 - [priority_mq] did on idle post a message? false
10:39:30 INFO  GeneralLocationListener.onGpsStatusChanged:143 - GPS started, waiting for fix
10:39:31 DEBUG GpsLoggingService.onLocationChanged:784 - Has description? false, Single point? false, Last timestamp: 1540978770400
10:39:31 DEBUG LocalX509TrustManager.isKnownServer:144 - Checking for certificate - HashCode: 26302702, Subject: CN=lopresti.[mydomain], in keystore: false
10:39:31 ERROR AppSettings$1.e:97 - error while executing job com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@f2f5cbb
javax.net.ssl.SSLHandshakeException: com.mendhak.gpslogger.common.network.CertificateValidationException: Certificate path validation error
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361) ~[na:0.0]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268) ~[na:0.0]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238) ~[na:0.0]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149) ~[na:0.0]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192) ~[na:0.0]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) ~[na:0.0]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) ~[na:0.0]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:0.0]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:0.0]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:0.0]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[na:0.0]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[na:0.0]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[na:0.0]
	at okhttp3.RealCall.execute(RealCall.java:69) ~[na:0.0]
	at com.mendhak.gpslogger.loggers.customurl.CustomUrlJob.onRun(CustomUrlJob.java:79) ~[na:0.0]
	at com.birbit.android.jobqueue.Job.safeRun(Job.java:229) ~[na:0.0]
	at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354) ~[na:0.0]
	at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:776) ~[na:0.0]
Caused by: java.security.cert.CertificateException: com.mendhak.gpslogger.common.network.CertificateValidationException: Certificate path validation error
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:617) ~[na:0.0]
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357) ~[na:0.0]
	... 28 common frames omitted
Caused by: com.mendhak.gpslogger.common.network.CertificateValidationException: Certificate path validation error
	at com.mendhak.gpslogger.common.network.LocalX509TrustManager.checkServerTrusted(LocalX509TrustManager.java:123) ~[na:0.0]
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:182) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596) ~[na:0.0]
	... 30 common frames omitted
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549) ~[na:0.0]
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401) ~[na:0.0]
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:287) ~[na:0.0]
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:113) ~[na:0.0]
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:87) ~[na:0.0]
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:116) ~[na:0.0]
	at com.mendhak.gpslogger.common.network.LocalX509TrustManager.checkServerTrusted(LocalX509TrustManager.java:112) ~[na:0.0]
	... 32 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 39 common frames omitted
10:39:31 DEBUG AppSettings$1.d:92 - safeRunResult for com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@f2f5cbb : false. re run:true. cancelled: false
```

Would that already help?

**Comment by mendhak** [comment]
Just tested the domain you sent.  I didn't need to validate the certificate.  I was able to send a few log points without errors.  (I sent it as `/?test=true`) 

I also did a check of the chain and the chain looks fine.  

Have you deleted the `.bks` file in your GPSLogger folder?

What is your Phone + OS version?  I tested with OnePlus 3T, Android 8.

**Comment by glpatcern** [comment]
Interesting. I had not deleted it before that attempt, now I did that and I do get the error - which then disappears once I validate the certificate once again. But indeed I understand that I should never need to validate the certificate.

This is with a Huawei Nova with Android 7.0, and `Digital Signature Trust Co.` is in the list of trusted credentials as mentioned earlier. I could extract the new debuglog if it can be of help.

**Comment by mendhak** [comment]
So I've been trying a few different things for a while, tried some old phones I had and some emulators, but I'm not able to get the same problem.  

One other thing I failed to take into account, is Chrome can have its own SSL engine so even on older Androids, the LE certs will work which is something they are able to accomplish via Google Play Services updates... so one thing that you can do is try your domain in a non-Chrome browser, like Firefox for Android.   

But that aside I don't have a way of grabbing the entire certificate chain, I can only grab the certificate itself but not the root CA, only can store the certificate as the thing that the user has accepted.

And just to confirm, the exact CA that you have in your list is `Digital SIgnature Trust Co.` with subtext - `DST Root CA X3`
