### ISSUE TITLE
error gpsLogging service

### ISSUE THREAD

**Issue by omidkarami77** [mendhak/gpslogger#946]
hi error android 12 to line 
            gpsLocationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 1000, 0, gpsLocationListener);
        at android.location.ILocationManager$Stub$Proxy.registerLocationListener(ILocationManager.java:1502)

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mendhak.gpslogger, PID: 8720
    java.lang.RuntimeException: Unable to start service com.mendhak.gpslogger.GpsLoggingService@dbd8b33 with Intent { cmp=com.mendhak.gpslogger/.GpsLoggingService }: java.lang.SecurityException: uid 10470 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5112)
        at android.app.ActivityThread.access$2200(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2321)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8641)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
     Caused by: java.lang.SecurityException: uid 10470 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
        at android.os.Parcel.createException(Parcel.java:2421)
        at android.os.Parcel.readException(Parcel.java:2404)
        at android.os.Parcel.readException(Parcel.java:2346)
        at android.location.ILocationManager$Stub$Proxy.registerLocationListener(ILocationManager.java:1502)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1499)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1187)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1152)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1123)
        at com.mendhak.gpslogger.GpsLoggingService.startGpsManager(GpsLoggingService.java:621)
        at com.mendhak.gpslogger.GpsLoggingService.startLogging(GpsLoggingService.java:409)
        at com.mendhak.gpslogger.GpsLoggingService.onStartCommand(GpsLoggingService.java:136)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5094)
        at android.app.ActivityThread.access$2200(ActivityThread.java:310) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2321) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8641) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.location.LocationPermissions.enforceLocationPermission(LocationPermissions.java:115)
        at com.android.server.location.LocationManagerService.registerLocationListener(LocationManagerService.java:1015)
        at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:609)
        at android.os.Binder.execTransactInternal(Binder.java:1215)
        at android.os.Binder.execTransact(Binder.java:1179)

**Comment by mendhak** [comment]
> uid 10470 does not have android.permission.ACCESS_COARSE_LOCATION or android.permission.ACCESS_FINE_LOCATION.

Looks like the app hasn't been granted permissions, or the permissions have been revoked.  Try reopening the application and you should get prompted to grant it permissions, or you can also grant it permissions from the settings apps area.
